export const DIR_RTL = 'rtl';
export const DIR_LTR = 'ltr';
export const MODE_LIGHT = 'light';
export const MODE_DARK = 'dark';

export const SIDE_NAV_WIDTH = 215;
export const SIDE_NAV_COLLAPSED_WIDTH = 70;
export const SPLITTED_SIDE_NAV_MINI_WIDTH = 70;
export const STACKED_SIDE_NAV_SECONDARY_WIDTH = 180;
export const SIDE_NAV_CONTENT_GUTTER = 'px-2';
export const LOGO_X_GUTTER = 'px-6';
export const HEADER_HEIGHT = 44;
export const PAGE_CONTAINER_GUTTER_X = 'px-1';
export const PAGE_CONTAINER_GUTTER_Y = 'py-1';

export const LAYOUT_FRAMELESS_SIDE = 'framelessSide';

export const THEME_ENUM = {
  DIR_RTL: DIR_RTL,
  DIR_LTR: DIR_LTR,
  MODE_LIGHT: MODE_LIGHT,
  MODE_DARK: MODE_DARK,
  SIDE_NAV_WIDTH: SIDE_NAV_WIDTH,
  SIDE_NAV_COLLAPSED_WIDTH: SIDE_NAV_COLLAPSED_WIDTH,
  SPLITTED_SIDE_NAV_MINI_WIDTH: SPLITTED_SIDE_NAV_MINI_WIDTH,
  STACKED_SIDE_NAV_SECONDARY_WIDTH: STACKED_SIDE_NAV_SECONDARY_WIDTH,
  HEADER_HEIGHT: HEADER_HEIGHT,
  LAYOUT_FRAMELESS_SIDE: LAYOUT_FRAMELESS_SIDE,
} as const;
