export enum EventList {
    LeadAssigned = "lead_assigned",
    LeadAssignmentAdmin = "lead_assignment_admin",
    AgentLogin = "agent_login",
    AgentLogout = "agent_logout",
    ProjectCreated = "project_created",
    ProjectAssigned = "project_assigned",
    LeadStatusChanged = "lead_status_changed",
    LeadConverted = "lead_converted",
    OfferCreated = "offer_created",
    OpeningCreated = "opening_created",
    ProviderApproved = "provider_approved",
    ProviderRejected = "provider_rejected",
    ProviderPayment = "provider_payment",
    CommissionEarned = "commission_earned",
    RevenueTargetMet = "revenue_target_met",
    SystemMaintenance = "system_maintenance",
    UserRoleChanged = "user_role_changed",
}