'use client';
// components/ApolloIcon.tsx (Enhanced Version)
import React from 'react';
import classNames from '../../../utils/classNames';

type ApolloIconProps = {
  name: keyof typeof APOLLO_ICONS;
  className?: string;
  ariaLabel?: string;
  onClick?: () => void;
};

/**
 * The keys are the icon names and the values are the unicode codes.
 */
export const APOLLO_ICONS = {
  '0-5x': '\uF101',
  '1-2x': '\uF103',
  '1-5x': '\uF104',
  '1-7x': '\uF105',
  '1-circle': '\uF102',
  '1x': '\uF106',
  '2-2x': '\uF108',
  '2-5x': '\uF109',
  '2-circle': '\uF107',
  '2x': '\uF10A',
  '3-circle': '\uF10B',
  '3x': '\uF10C',
  '4-circle': '\uF10D',
  'add-to-playlist': '\uF10E',
  'ai-email': '\uF10F',
  'ai-personalization': '\uF110',
  'ai-stars': '\uF113',
  'ai-stars-filled': '\uF111',
  'ai-stars-outline': '\uF112',
  'alert-bell': '\uF114',
  'alert-circle': '\uF115',
  'alert-triangle': '\uF116',
  alexa: '\uF117',
  'angel-list': '\uF118',
  anthropic: '\uF119',
  apollo: '\uF11D',
  'apollo-ai': '\uF11A',
  'apollo-full-logo': '\uF11B',
  'apollo-logo': '\uF11C',
  'archive-box': '\uF11E',
  'area-chart': '\uF11F',
  'arrow-corner-up-right': '\uF120',
  'arrow-down': '\uF121',
  'arrow-left': '\uF122',
  'arrow-right': '\uF123',
  'arrow-up': '\uF125',
  'arrow-up-circle': '\uF124',
  'arrows-merge': '\uF126',
  associate: '\uF127',
  association: '\uF128',
  'auto-flash': '\uF129',
  ban: '\uF12A',
  'bar-chart-axis': '\uF12C',
  'bar-chart-axis-horizontal': '\uF12B',
  'bar-chart-horz': '\uF12D',
  bell: '\uF12F',
  'bell-slash': '\uF12E',
  bold: '\uF130',
  'book-open': '\uF131',
  'bookmark-filled': '\uF132',
  'bookmark-outline': '\uF133',
  'box-product': '\uF134',
  briefcase: '\uF135',
  'bubble-question': '\uF136',
  bug: '\uF137',
  'bulleted-list': '\uF138',
  calendar: '\uF142',
  'calendar-associate': '\uF139',
  'calendar-backwards': '\uF13A',
  'calendar-check': '\uF13B',
  'calendar-clock': '\uF13C',
  'calendar-forward': '\uF13D',
  'calendar-question': '\uF13E',
  'calendar-rewind': '\uF13F',
  'calendar-slash': '\uF140',
  'calendar-warning': '\uF141',
  'camera-reel': '\uF143',
  'caret-down-small': '\uF144',
  'caret-left': '\uF146',
  'caret-left-small': '\uF145',
  'caret-right': '\uF148',
  'caret-right-small': '\uF147',
  'caret-up-small': '\uF149',
  'chart-line': '\uF14A',
  check: '\uF152',
  'check-circle': '\uF14D',
  'check-circle-fill': '\uF14B',
  'check-circle-task': '\uF14C',
  'check-square': '\uF150',
  'check-square-fill': '\uF14E',
  'check-square-task': '\uF14F',
  'check-table': '\uF151',
  'checkbox-alt1': '\uF153',
  'checkbox-alt2': '\uF154',
  'checkbox-list': '\uF155',
  checklist: '\uF156',
  'chevron-arrow-down': '\uF158',
  'chevron-arrow-down-circle': '\uF157',
  'chevron-arrow-left': '\uF159',
  'chevron-arrow-right': '\uF15A',
  'chevron-arrow-up': '\uF15B',
  circle: '\uF15D',
  'circle-down-small': '\uF15C',
  'clock-eight': '\uF15E',
  'cloud-check': '\uF15F',
  'cloud-computing': '\uF160',
  'cloud-data-tree': '\uF161',
  'cloud-download': '\uF162',
  'cloud-upload': '\uF163',
  cockpit: '\uF164',
  code: '\uF166',
  'code-branch': '\uF165',
  cog: '\uF168',
  'cog-check': '\uF167',
  coins: '\uF169',
  'column-chart': '\uF16A',
  combine: '\uF16B',
  'command-v': '\uF16D',
  'command-v-alt': '\uF16C',
  comment: '\uF170',
  'comment-add': '\uF16E',
  'comment-slash': '\uF16F',
  company: '\uF17E',
  'company-check-colored': '\uF171',
  'company-cog': '\uF172',
  'company-download-colored': '\uF173',
  'company-error-colored': '\uF174',
  'company-info-colored': '\uF175',
  'company-multiple': '\uF176',
  'company-plus': '\uF177',
  'company-progress-colored': '\uF178',
  'company-question-colored': '\uF179',
  'company-remove': '\uF17A',
  'company-star': '\uF17B',
  'company-table': '\uF17D',
  'contact-role': '\uF17F',
  copy: '\uF180',
  'credit-card-off': '\uF181',
  'credit-card-plus': '\uF182',
  'credit-card-search': '\uF183',
  cross: '\uF184',
  'csv-doc': '\uF185',
  cursor: '\uF186',
  'custom-fields': '\uF187',
  'dashboard-plus': '\uF188',
  'data-hourglass': '\uF189',
  'data-monitor': '\uF18A',
  'data-sync': '\uF18B',
  desktop: '\uF18C',
  diagnose: '\uF18D',
  dialpad: '\uF18E',
  diamond: '\uF18F',
  dollar: '\uF194',
  'dollar-circle': '\uF190',
  'dollar-kanban': '\uF191',
  'dollar-square': '\uF192',
  'dollar-table': '\uF193',
  'donut-chart': '\uF195',
  'double-arrow-down': '\uF196',
  'double-arrow-left': '\uF197',
  'double-arrow-right': '\uF198',
  'double-arrow-up': '\uF199',
  download: '\uF19A',
  'drag-and-sort': '\uF19B',
  'drag-reorder': '\uF19C',
  'dropdown-large': '\uF19D',
  'dropdown-up-large': '\uF19E',
  'dynamic-variable': '\uF19F',
  ellipse: '\uF1A0',
  'email-check': '\uF1A1',
  'email-error': '\uF1A2',
  'email-info-colored': '\uF1A3',
  'email-manual': '\uF1A4',
  'email-progress': '\uF1A5',
  'email-question': '\uF1A6',
  'email-star-outline': '\uF1A7',
  'email-table': '\uF1A9',
  'emoji-annoyed-face': '\uF1AA',
  'emoji-happy-face': '\uF1AB',
  'emoji-sad-face': '\uF1AC',
  'enrichment-refresh': '\uF1AD',
  exchange: '\uF1AE',
  'external-link': '\uF1AF',
  'eye-filled': '\uF1B0',
  'eye-slash': '\uF1B2',
  facebook: '\uF1B4',
  'facebook-square-filled': '\uF1B3',
  file: '\uF1BA',
  'file-alt': '\uF1B5',
  'file-check': '\uF1B6',
  'file-edit': '\uF1B7',
  'file-lock': '\uF1B8',
  'file-upload': '\uF1B9',
  filter: '\uF1BC',
  'filter-slider': '\uF1BB',
  flag: '\uF1BD',
  folder: '\uF1C0',
  'folder-open': '\uF1BE',
  'folder-plus': '\uF1BF',
  'forward-10': '\uF1C1',
  function: '\uF1C2',
  'funnel-chart': '\uF1C3',
  'generate-pipeline': '\uF1C4',
  gift: '\uF1C5',
  globe: '\uF1C6',
  google: '\uF1CA',
  'google-chrome': '\uF1C7',
  'google-logo': '\uF1C8',
  'google-meet': '\uF1C9',
  'graduation-cap': '\uF1CB',
  greenhouse: '\uF1CC',
  grid: '\uF1CE',
  'grid-plus': '\uF1CD',
  'growth-down': '\uF1CF',
  'growth-up': '\uF1D0',
  'hand-waving': '\uF1D1',
  'hard-bounce': '\uF1D2',
  'heartbeat-status': '\uF1D3',
  heatmap: '\uF1D4',
  'hide-arrow-left': '\uF1D5',
  'hide-arrow-right': '\uF1D6',
  'hierarchy-child': '\uF1D7',
  'hierarchy-parent': '\uF1D9',
  'hierarchy-parent-child': '\uF1D8',
  history: '\uF1DA',
  home: '\uF1DB',
  hubspot: '\uF1DD',
  'hubspot-failed': '\uF1DC',
  'image-placeholder': '\uF1DE',
  industry: '\uF1DF',
  'info-circle': '\uF1E0',
  'intent-data': '\uF1E1',
  italic: '\uF1E2',
  'key-inclined': '\uF1E3',
  language: '\uF1E4',
  languages: '\uF1E5',
  'laptop-computer': '\uF1E6',
  'layer-group': '\uF1E7',
  layout: '\uF1E8',
  'learn-more': '\uF1E9',
  'life-buoy': '\uF1EA',
  lightbulb: '\uF1EB',
  lightning: '\uF1EC',
  link: '\uF1F0',
  'link-off': '\uF1ED',
  'link-plus': '\uF1EE',
  'link-square-filled': '\uF1EF',
  'list-check': '\uF1F1',
  'list-checked': '\uF1F2',
  'list-deselect': '\uF1F3',
  'list-ordered': '\uF1F4',
  'list-plus': '\uF1F5',
  'list-table-view': '\uF1F6',
  'list-times': '\uF1F7',
  'list-ui': '\uF1F8',
  loading: '\uF1F9',
  location: '\uF1FA',
  'log-in': '\uF1FB',
  'log-out': '\uF1FC',
  'magic-rewriting': '\uF1FD',
  'magic-wand': '\uF1FE',
  magnet: '\uF1FF',
  mail: '\uF212',
  'mail-block': '\uF200',
  'mail-download-colored': '\uF201',
  'mail-envelope-question': '\uF203',
  'mail-filled': '\uF204',
  'mail-info': '\uF205',
  'mail-lock': '\uF206',
  'mail-minus': '\uF208',
  'mail-minus-colored': '\uF207',
  'mail-open': '\uF209',
  'mail-plus-colored': '\uF20A',
  'mail-search-colored-1': '\uF20B',
  'mail-star-colored': '\uF20D',
  'mail-times': '\uF20F',
  'mail-times-colored': '\uF20E',
  'mail-upload': '\uF211',
  'mail-upload-colored': '\uF210',
  mailgun: '\uF213',
  mails: '\uF214',
  'mastercard-logo': '\uF215',
  maximize: '\uF217',
  'maximize-screen': '\uF216',
  medal: '\uF218',
  'meeting-source': '\uF219',
  menu: '\uF21A',
  'mic-on': '\uF21B',
  'mic-slash': '\uF21C',
  'microsoft-teams': '\uF21D',
  minimize: '\uF21F',
  'minimize-screen': '\uF21E',
  minus: '\uF221',
  'minus-circle': '\uF220',
  mobile: '\uF222',
  'money-bag': '\uF223',
  'money-stack': '\uF224',
  moon: '\uF225',
  'more-h': '\uF226',
  'mouse-pointer': '\uF227',
  move: '\uF228',
  'multi-credit': '\uF229',
  'multi-line-text': '\uF22A',
  'multi-split': '\uF22B',
  mute: '\uF22C',
  'nested-circles': '\uF22D',
  'news-filter': '\uF22E',
  'no-email-available': '\uF22F',
  'no-video-camera': '\uF230',
  notes: '\uF233',
  'notes-check': '\uF231',
  'notes-plus': '\uF232',
  number: '\uF234',
  openai: '\uF235',
  'ordered-list': '\uF236',
  outreach: '\uF237',
  padlock: '\uF238',
  paperclip: '\uF239',
  pause: '\uF23B',
  'pause-circle': '\uF23A',
  pen: '\uF23C',
  perplexity: '\uF23D',
  'persistent-checklist': '\uF23E',
  phone: '\uF24B',
  'phone-check': '\uF23F',
  'phone-decline': '\uF240',
  'phone-download': '\uF242',
  'phone-download-colored': '\uF241',
  'phone-error': '\uF243',
  'phone-in': '\uF244',
  'phone-info-colored': '\uF245',
  'phone-out': '\uF246',
  'phone-progress': '\uF247',
  'phone-question-colored': '\uF248',
  'phone-table': '\uF249',
  'phone-times': '\uF24A',
  picture: '\uF24D',
  'picture-in-picture': '\uF24C',
  'pie-chart': '\uF24F',
  'pie-chart-2': '\uF24E',
  pipedrive: '\uF251',
  'pipedrive-failed': '\uF250',
  pipeline: '\uF252',
  play: '\uF254',
  'play-circle': '\uF253',
  'player-in-player': '\uF255',
  plus: '\uF258',
  'plus-circle': '\uF257',
  'plus-circle-filled': '\uF256',
  pointer: '\uF259',
  powerup_ai: '\uF25A',
  powerup_icon: '\uF25B',
  puzzle: '\uF25C',
  'question-circle': '\uF25E',
  'question-circle-filled': '\uF25D',
  record: '\uF25F',
  redo: '\uF260',
  refresh: '\uF261',
  'remove-from-playlist': '\uF262',
  reorder: '\uF263',
  repeat: '\uF264',
  reply: '\uF265',
  'rewind-10': '\uF266',
  rocket: '\uF267',
  'rotate-left': '\uF268',
  'rotate-right': '\uF269',
  salesforce: '\uF26A',
  salesloft: '\uF26B',
  scissors: '\uF26C',
  score: '\uF26D',
  search: '\uF272',
  'search-checked': '\uF26E',
  'search-companies': '\uF26F',
  'search-cross': '\uF270',
  'search-user': '\uF271',
  'send-inclined': '\uF273',
  sendgrid: '\uF274',
  sequence: '\uF27B',
  'sequence-check': '\uF275',
  'sequence-error': '\uF276',
  'sequence-play': '\uF277',
  'sequence-question': '\uF278',
  'sequence-sending-progress': '\uF279',
  'sequence-table': '\uF27A',
  'server-database': '\uF27C',
  share: '\uF27D',
  shield: '\uF27E',
  'sic-code': '\uF27F',
  'sidebar-collapse': '\uF280',
  'sidebar-expand': '\uF281',
  'signal-1': '\uF282',
  'signal-2': '\uF283',
  'signal-3': '\uF284',
  signals: '\uF285',
  'single-credit': '\uF286',
  'skip-forward': '\uF287',
  'sliders-settings': '\uF288',
  'sort-accending': '\uF289',
  'sort-ascending': '\uF28A',
  'sort-decending': '\uF28B',
  'sort-descending': '\uF28C',
  'spot-create-alert': '\uF28D',
  'star-empty': '\uF28E',
  'star-filled': '\uF28F',
  'status-activity': '\uF290',
  'stop-circle': '\uF291',
  stopwatch: '\uF292',
  strikethrough: '\uF293',
  sum: '\uF294',
  sun: '\uF295',
  support: '\uF296',
  swatch: '\uF297',
  'table-file': '\uF298',
  tag: '\uF29A',
  'tag-user': '\uF299',
  talking: '\uF29B',
  'text-title': '\uF29C',
  'thumbs-down': '\uF29E',
  'thumbs-down-filled': '\uF29D',
  'thumbs-up': '\uF2A0',
  'thumbs-up-filled': '\uF29F',
  thumbtack: '\uF2A1',
  tiles: '\uF2A2',
  times: '\uF2A5',
  'times-circle': '\uF2A4',
  'toggle-list': '\uF2A6',
  token: '\uF2A7',
  'traffic-light': '\uF2A8',
  trash: '\uF2A9',
  'trello-board': '\uF2AA',
  trigger: '\uF2AB',
  trophy: '\uF2AE',
  'trophy-filled': '\uF2AC',
  'trophy-sales': '\uF2AD',
  'true-false': '\uF2AF',
  twitter: '\uF2B1',
  'twitter-square-filled': '\uF2B0',
  underline: '\uF2B2',
  undo: '\uF2B3',
  unflag: '\uF2B4',
  unverified: '\uF2B5',
  'up-down-caret': '\uF2B6',
  'update-required': '\uF2B7',
  upload: '\uF2B8',
  user: '\uF2C8',
  'user-bubble': '\uF2B9',
  'user-check': '\uF2BA',
  'user-circle': '\uF2BB',
  'user-download-colored': '\uF2BC',
  'user-exclamation': '\uF2BD',
  'user-filled': '\uF2BE',
  'user-minus': '\uF2BF',
  'user-plus': '\uF2C0',
  'user-question': '\uF2C1',
  'user-refresh': '\uF2C2',
  'user-square': '\uF2C3',
  'user-star': '\uF2C4',
  'user-talking': '\uF2C5',
  'user-times': '\uF2C6',
  'user-upload': '\uF2C7',
  users: '\uF2C9',
  vector: '\uF2CA',
  'video-camera': '\uF2CD',
  'video-camera-off': '\uF2CC',
  'video-pause': '\uF2CE',
  'video-play': '\uF2CF',
  'view-grid-list': '\uF2D0',
  'view-list': '\uF2D1',
  volume: '\uF2D2',
  wallet: '\uF2D3',
  waterfall: '\uF2D4',
  'website-visitors': '\uF2D5',
  'window-equal': '\uF2D6',
  'window-maximize': '\uF2D7',
  'window-minimize': '\uF2D8',
  world: '\uF2D9',
  wrench: '\uF2DA',
  x: '\uF2DB',
  yelp: '\uF2DC',
  zoom: '\uF2DD',
} as const;

/**
 *
 * Required props:
 * - either `code` or `name`
 */
export const ApolloIcon: React.FC<ApolloIconProps> = ({
  name,
  className = '',
  ariaLabel,
  onClick,
  ...props
}) => {
  const normalizeCode = (input: string): string => {
    return input
      .replace(/^(\\|U\+|0x)/i, '')
      .toUpperCase()
      .padStart(4, '0');
  };

  const getCharacter = (unicodeCode: string): string => {
    try {
      const normalized = normalizeCode(unicodeCode);
      const decimal = parseInt(normalized, 16);
      return String.fromCharCode(decimal);
    } catch {
      console.warn(`Invalid Unicode code: ${unicodeCode}`);
      return '?';
    }
  };

  return (
    <>
      <span
        aria-label={ariaLabel}
        role={ariaLabel ? 'img' : undefined}
        aria-hidden={!ariaLabel}
        onClick={onClick}
        className={classNames(
          'font-apollo-icon inline-flex items-center justify-center leading-none font-normal select-none',
          onClick && 'cursor-pointer',
          className
        )}
        {...props}
      >
        {name ? APOLLO_ICONS[name] : getCharacter(name)}
      </span>
    </>
  );
};

export default ApolloIcon;
