/**
 * Convenience hook - same API as old useUnifiedDashboardState but reads from Zustand store.
 * Use within UnifiedDashboardStoreProvider.
 */
import { useShallow } from 'zustand/react/shallow';
import { useUnifiedDashboardStore } from './unifiedDashboardStore';

export function useUnifiedDashboardStateFromStore() {
  return useUnifiedDashboardStore(
    useShallow((s) => ({
      selectedProgressFilter: s.selectedProgressFilter,
      setSelectedProgressFilter: s.setSelectedProgressFilter,
      createOpeningOpen: s.createOpeningOpen,
      setCreateOpeningOpen: s.setCreateOpeningOpen,
      createConfirmationDialogOpen: s.createConfirmationDialogOpen,
      setCreateConfirmationDialogOpen: s.setCreateConfirmationDialogOpen,
      isPaymentVoucherDialogOpen: s.isPaymentVoucherDialogOpen,
      setIsPaymentVoucherDialogOpen: s.setIsPaymentVoucherDialogOpen,
      isDocsModalOpen: s.isDocsModalOpen,
      setIsDocsModalOpen: s.setIsDocsModalOpen,
      selectedOfferForDocs: s.selectedOfferForDocs,
      setSelectedOfferForDocs: s.setSelectedOfferForDocs,
      isEditOfferDialogOpen: s.isEditOfferDialogOpen,
      setIsEditOfferDialogOpen: s.setIsEditOfferDialogOpen,
      selectedOfferForEdit: s.selectedOfferForEdit,
      setSelectedOfferForEdit: s.setSelectedOfferForEdit,
      expandedRowId: s.expandedRowId,
      setExpandedRowId: s.setExpandedRowId,
      forceUpdate: s.forceUpdate,
      setForceUpdate: s.setForceUpdate,
      isBulkUpdateDialogOpen: s.isBulkUpdateDialogOpen,
      setIsBulkUpdateDialogOpen: s.setIsBulkUpdateDialogOpen,
      isNettoDialogOpen: s.isNettoDialogOpen,
      setIsNettoDialogOpen: s.setIsNettoDialogOpen,
      isBulkNettoDialogOpen: s.isBulkNettoDialogOpen,
      setIsBulkNettoDialogOpen: s.setIsBulkNettoDialogOpen,
      isLostDialogOpen: s.isLostDialogOpen,
      setIsLostDialogOpen: s.setIsLostDialogOpen,
      isSendToOutDialogOpen: s.isSendToOutDialogOpen,
      setIsSendToOutDialogOpen: s.setIsSendToOutDialogOpen,
      isPdfModalOpen: s.isPdfModalOpen,
      setIsPdfModalOpen: s.setIsPdfModalOpen,
      selectedRowForPdf: s.selectedRowForPdf,
      setSelectedRowForPdf: s.setSelectedRowForPdf,
      isOpeningDetailsOpen: s.isOpeningDetailsOpen,
      setIsOpeningDetailsOpen: s.setIsOpeningDetailsOpen,
      selectedOpeningForDetails: s.selectedOpeningForDetails,
      setSelectedOpeningForDetails: s.setSelectedOpeningForDetails,
      isOfferDetailsOpen: s.isOfferDetailsOpen,
      setIsOfferDetailsOpen: s.setIsOfferDetailsOpen,
      selectedOfferForDetails: s.selectedOfferForDetails,
      setSelectedOfferForDetails: s.setSelectedOfferForDetails,
      isPdfConfirmationModalOpen: s.isPdfConfirmationModalOpen,
      setIsPdfConfirmationModalOpen: s.setIsPdfConfirmationModalOpen,
      selectedRowForPdfConfirmation: s.selectedRowForPdfConfirmation,
      setSelectedRowForPdfConfirmation: s.setSelectedRowForPdfConfirmation,
      hasManuallyClearedGroupFilter: s.hasManuallyClearedGroupFilter,
      setHasManuallyClearedGroupFilter: s.setHasManuallyClearedGroupFilter,
      isMultiLevelGroupingApplied: s.isMultiLevelGroupingApplied,
      setIsMultiLevelGroupingApplied: s.setIsMultiLevelGroupingApplied,
      hasTransferredOffer: s.hasTransferredOffer,
      setHasTransferredOffer: s.setHasTransferredOffer,
      isAssignTicketDialogOpen: s.isAssignTicketDialogOpen,
      setIsAssignTicketDialogOpen: s.setIsAssignTicketDialogOpen,
      selectedTicketForAssign: s.selectedTicketForAssign,
      setSelectedTicketForAssign: s.setSelectedTicketForAssign,
      isBulkDownloadConfirmOpen: s.isBulkDownloadConfirmOpen,
      setIsBulkDownloadConfirmOpen: s.setIsBulkDownloadConfirmOpen,
      isBulkDownloading: s.isBulkDownloading,
      setIsBulkDownloading: s.setIsBulkDownloading,
      bulkDownloadConfirmData: s.bulkDownloadConfirmData,
      setBulkDownloadConfirmData: s.setBulkDownloadConfirmData,
      isNavigating: false,
    }))
  );
}
