import type { NavigationTree } from '@/@types/navigation';
import {
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_TITLE,
} from '@/constants/navigation.constant';
import { ADMIN_PREFIX_PATH, DASHBOARDS_PREFIX_PATH } from '@/constants/route.constant';
import { Role } from './auth.route.config';

const adminNavigationConfig: NavigationTree[] = [
  {
    key: 'communications',
    path: '',
    title: 'Communications',
    translateKey: 'nav.communications',
    icon: 'dashboardCommunications',
    type: NAV_ITEM_TYPE_TITLE,
    authority: [Role.ADMIN, Role.PROVIDER],
    subMenu: [
      {
        key: 'dashboard.calls',
        path: `${DASHBOARDS_PREFIX_PATH}/calls`,
        title: 'Calls',
        translateKey: 'nav.dashboard.calls',
        icon: 'dashboardCalls',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN],
        subMenu: [],
      },
    ],
  },
  {
    key: 'admin.configurations',
    path: '',
    title: 'Admin Menu',
    translateKey: 'nav.admin.admin',
    icon: 'accountSettings',
    type: NAV_ITEM_TYPE_TITLE,
    authority: [Role.ADMIN],
    subMenu: [
      {
        key: 'admin.tenants',
        path: `${ADMIN_PREFIX_PATH}/tenants`,
        title: 'Tenants',
        translateKey: 'nav.admin.tenants',
        icon: 'company',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN],
        subMenu: [],
      },
      {
        key: 'admin.users',
        path: '',
        title: 'Users',
        translateKey: 'nav.admin.users.users',
        icon: 'dashboardUsers',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN],
        subMenu: [
          {
            key: 'admin.users.allUsers',
            path: `${ADMIN_PREFIX_PATH}/users`,
            title: 'All Users',
            translateKey: 'nav.admin.users.allUsers',
            icon: 'dashboardUsers',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.users.create',
            path: `${ADMIN_PREFIX_PATH}/users/create`,
            title: 'Create User',
            translateKey: 'nav.admin.users.create',
            icon: 'dashboardUsers',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.roles',
            path: `${ADMIN_PREFIX_PATH}/roles`,
            title: 'Permissions',
            translateKey: 'nav.admin.permissions',
            icon: 'usersPermissionsIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.offices',
            path: `${ADMIN_PREFIX_PATH}/offices`,
            title: 'Offices',
            translateKey: 'nav.admin.offices',
            icon: 'officesIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
        ],
      },
      {
        key: 'admin.configurations',
        path: '',
        title: 'Settings',
        translateKey: 'nav.admin.settings',
        icon: 'accountSettings',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN],
        subMenu: [
          {
            key: 'admin.banks',
            path: `${ADMIN_PREFIX_PATH}/banks`,
            title: 'Banks',
            translateKey: 'nav.admin.banks',
            icon: 'bank',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.sources',
            path: `${ADMIN_PREFIX_PATH}/sources`,
            title: 'Sources',
            translateKey: 'nav.admin.sources',
            icon: 'tag',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },

          {
            key: 'admin.mailservers',
            path: `${ADMIN_PREFIX_PATH}/mailservers`,
            title: 'Mail Servers',
            translateKey: 'nav.admin.mailservers',
            icon: 'mail',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.voipservers',
            path: `${ADMIN_PREFIX_PATH}/voip-servers`,
            title: 'VOIP Servers',
            translateKey: 'nav.admin.voipservers',
            icon: 'phone',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },

          {
            key: 'admin.paymentterms',
            path: `${ADMIN_PREFIX_PATH}/payment-terms`,
            title: 'Payment Terms',
            translateKey: 'nav.admin.paymentterms',
            icon: 'payment',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.bonusamount',
            path: `${ADMIN_PREFIX_PATH}/bonus-amount`,
            title: 'Bonus Amount',
            translateKey: 'nav.admin.bonusamount',
            icon: 'wallet',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.stages',
            path: `${ADMIN_PREFIX_PATH}/stages`,
            title: 'Stages',
            translateKey: 'nav.admin.stages',
            icon: 'layer-group',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },

          {
            key: 'admin.predefined-tasks',
            path: `${ADMIN_PREFIX_PATH}/predefined-tasks`,
            title: 'Predefined Tasks',
            translateKey: 'nav.admin.predefined-tasks',
            icon: 'todoIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.email-templates',
            path: `${ADMIN_PREFIX_PATH}/email-templates`,
            title: 'Email Templates',
            translateKey: 'nav.admin.email-templates',
            icon: 'file-alt',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.pdf-templates',
            path: `${ADMIN_PREFIX_PATH}/pdf`,
            title: 'PDF Templates',
            translateKey: 'nav.admin.pdf-templates',
            icon: 'file',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.security',
            path: `${ADMIN_PREFIX_PATH}/security`,
            title: 'Security',
            translateKey: 'nav.admin.security',
            icon: 'security',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.tablesettings',
            path: `${ADMIN_PREFIX_PATH}/table-settings`,
            title: 'Table Settings',
            translateKey: 'nav.admin.tablesettings',
            icon: 'sliders-settings',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.bot-setting',
            path: `${ADMIN_PREFIX_PATH}/settings`,
            title: 'Bot Setting',
            translateKey: 'nav.admin.bot-setting',
            icon: 'accountSettings',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
        //   {
        //     key: 'admin.manage-leadbot',
        //     path: `${ADMIN_PREFIX_PATH}/manage-leadbot`,
        //     title: 'Manage Leadbot',
        //     translateKey: 'nav.admin.manage-leadbot',
        //     icon: 'apollo-ai',
        //     type: NAV_ITEM_TYPE_ITEM,
        //     authority: [Role.ADMIN],
        //     subMenu: [],
        //   },
          {
            key: 'admin.notification-rules',
            path: `${ADMIN_PREFIX_PATH}/notification-rules`,
            title: 'Notification Rules',
            translateKey: 'nav.admin.notification-rules',
            icon: 'notification',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.form-leads',
            path: `${ADMIN_PREFIX_PATH}/form-leads`,
            title: 'Form Leads',
            translateKey: 'nav.admin.form-leads',
            icon: 'file-alt',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'admin.form-lead-config',
            path: `${ADMIN_PREFIX_PATH}/form-lead-config`,
            title: 'Form Lead Config',
            translateKey: 'nav.admin.form-lead-config',
            icon: 'sliders-settings',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
        ],
      },
    ],
  },
  {
    key: 'admin.reportings',
    path: `${ADMIN_PREFIX_PATH}/reportings`,
    title: 'Reportings',
    translateKey: 'nav.admin.reportings',
    icon: 'ChartBarIcon',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [Role.ADMIN],
    subMenu: [],
  },
];

export default adminNavigationConfig;
