import { ADMIN_PREFIX_PATH, DASHBOARDS_PREFIX_PATH } from '@/constants/route.constant';
import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant';
import type { NavigationTree } from '@/@types/navigation';
import { Role } from './auth.route.config';

// test comming
//this is navMenu config
const dashboardsNavigationConfig: NavigationTree[] = [
  {
    key: 'dashboard',
    path: '',
    title: 'Workflow',
    translateKey: 'nav.dashboard.dashboard',
    icon: '',
    type: NAV_ITEM_TYPE_TITLE,
    authority: [...Object.values(Role)],
    meta: {
      horizontalMenu: {
        layout: 'default',
      },
    },
    subMenu: [
      {
        key: 'admin.import-leads',
        path: `${ADMIN_PREFIX_PATH}/import-leads`,
        title: 'Import',
        translateKey: 'nav.admin.import-leads',
        icon: 'dashboardImportLeads',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN],
        subMenu: [],
      },
      //   {
      //     key: 'admin.recentImports',
      //     path: `${ADMIN_PREFIX_PATH}/recent-imports`,
      //     title: 'recentImports',
      //     translateKey: 'nav.admin.recentImports',
      //     icon: 'dashboardRecentImport',
      //     type: NAV_ITEM_TYPE_ITEM,
      //     authority: [Role.ADMIN],
      //     subMenu: [],
      //   },
      {
        key: 'dashboard.home',
        path: `${DASHBOARDS_PREFIX_PATH}/home`,
        title: 'Home',
        translateKey: 'nav.dashboard.home',
        icon: 'dashboardHome',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.PROVIDER],
        subMenu: [],
      },
      {
        key: 'dashboard.leads',
        path: '',
        title: 'Leads',
        translateKey: 'nav.dashboard.leads.leads',
        icon: 'dashboardLeads',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN],
        subMenu: [
          {
            key: 'dashboard.leads.allLeads',
            path: `${DASHBOARDS_PREFIX_PATH}/leads`,
            title: 'All Leads',
            translateKey: 'nav.dashboard.leads.allLeads',
            icon: 'allLeadsIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'dashboard.leads.leadsBank',
            path: `${DASHBOARDS_PREFIX_PATH}/leads-bank`,
            title: 'Leads Bank',
            translateKey: 'nav.dashboard.leads.leadsBank',
            icon: 'leadsBankIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'dashboard.leads.pendingLeads',
            path: `${DASHBOARDS_PREFIX_PATH}/leads/pending-leads`,
            title: 'Pending Leads',
            translateKey: 'nav.dashboard.leads.pendingLeads',
            icon: 'pendingLeadsIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'dashboard.leads.archivedLeads',
            path: `${DASHBOARDS_PREFIX_PATH}/leads/archived`,
            title: 'Archived Leads',
            translateKey: 'nav.dashboard.leads.archivedLeads',
            icon: 'archivedLeadsIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'dashboard.leads.liveLeads',
            path: `${DASHBOARDS_PREFIX_PATH}/live-leads`,
            title: 'Live',
            translateKey: 'nav.dashboard.liveLeads',
            icon: 'liveLeadsIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'dashboard.leads.recycleLeads',
            path: `${DASHBOARDS_PREFIX_PATH}/recycle-leads`,
            title: 'Recycle',
            translateKey: 'nav.dashboard.recycleLeads',
            icon: 'recycleLeadsIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          // Tickets removed from Leads dropdown - now in main nav menu
          // {
          //   key: 'dashboard.tickets',
          //   path: `${DASHBOARDS_PREFIX_PATH}/tickets`,
          //   title: 'Tickets',
          //   translateKey: 'nav.dashboard.tickets',
          //   icon: 'todoIcon',
          //   type: NAV_ITEM_TYPE_ITEM,
          //   authority: [Role.ADMIN],
          //   subMenu: [],
          // },
          // {
          //   key: 'dashboard.leads.leadProjects',
          //   path: `${DASHBOARDS_PREFIX_PATH}/leads/projects`,
          //   title: 'Leads Project',
          //   translateKey: 'nav.dashboard.leads.leadsProject',
          //   icon: 'dashboardLeads',
          //   type: NAV_ITEM_TYPE_ITEM,
          //   authority: [Role.ADMIN],
          //   subMenu: [],
          // },
        ],
      },
      {
        key: 'dashboard.calling',
        path: '',
        title: 'Leads',
        translateKey: 'nav.dashboard.calling',
        icon: 'dashboardLeads',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.AGENT],
        subMenu: [
          {
            key: 'dashboard.agentLiveLeads',
            path: `${DASHBOARDS_PREFIX_PATH}/live-leads`,
            title: 'Live',
            translateKey: 'nav.dashboard.agentLiveLeads',
            icon: 'agentLiveLeadsIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.AGENT],
            subMenu: [],
          },
          {
            key: 'dashboard.agentRecycleLeads',
            path: `${DASHBOARDS_PREFIX_PATH}/recycle-leads`,
            title: 'Recycle',
            translateKey: 'nav.dashboard.agentRecycleLeads',
            icon: 'agentRecycleLeadsIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.AGENT],
            subMenu: [],
          },
          {
            key: 'dashboard.agentOutLeads',
            path: `${DASHBOARDS_PREFIX_PATH}/leads/archived`,
            title: 'Out',
            translateKey: 'nav.dashboard.agentOutLeads',
            icon: 'outOffersIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.AGENT],
            subMenu: [],
          },
          {
            key: 'dashboard.agentReclamations',
            path: `${DASHBOARDS_PREFIX_PATH}/reclamations`,
            title: 'Reclamations',
            translateKey: 'nav.dashboard.reclamations.allReclamations',
            icon: 'dashboardReclamations',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.AGENT],
            subMenu: [],
          },
        ],
      },
      {
        key: 'dashboard.offers',
        path: '',
        title: 'Offers',
        translateKey: 'nav.dashboard.offers',
        icon: 'dashboardOffers',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN, Role.AGENT],
        subMenu: [
          {
            key: 'dashboard.offers.allOffers',
            path: `${DASHBOARDS_PREFIX_PATH}/offers`,
            title: 'Offers',
            translateKey: 'nav.dashboard.offersSub.allOffers',
            icon: 'dashboardOffers',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.AGENT],
            subMenu: [],
          },
          {
            key: 'dashboard.offers.outOffers',
            path: `${DASHBOARDS_PREFIX_PATH}/out-offers`,
            title: 'Out Offers',
            translateKey: 'nav.dashboard.offersSub.outOffers',
            icon: 'outOffersIcon',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.AGENT],
            subMenu: [],
          },
        ],
      },
      {
        key: 'dashboard.holds',
        path: `${DASHBOARDS_PREFIX_PATH}/termin`,
        title: 'Meetings',
        translateKey: 'nav.dashboard.termin',
        icon: 'calendar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN, Role.AGENT],
        subMenu: [],
      },
      {
        key: 'dashboard.calendar',
        path: `${DASHBOARDS_PREFIX_PATH}/calendar`,
        title: 'Calendar',
        translateKey: 'nav.dashboard.calendar',
        icon: 'scheduledLeadsIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN, Role.AGENT],
        subMenu: [],
      },
      {
        key: 'dashboard.kanban',
        path: `${DASHBOARDS_PREFIX_PATH}/kanban`,
        title: 'Kanban',
        translateKey: 'nav.dashboard.kanban',
        icon: 'todoIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN, Role.AGENT],
        subMenu: [],
      },

      {
        key: 'dashboard.mails',
        path: `${DASHBOARDS_PREFIX_PATH}/mails`,
        title: 'Mails',
        translateKey: 'nav.dashboard.mails',
        icon: 'dashboardMails',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN, Role.PROVIDER, Role.AGENT],
        subMenu: [],
      },
      // {
      //   key: 'dashboard.cashflow',
      //   path: `${DASHBOARDS_PREFIX_PATH}/cashflow`,
      //   title: 'Cashflow',
      //   translateKey: 'nav.dashboard.cashflow',
      //   icon: 'dashboardCashflow',
      //   type: NAV_ITEM_TYPE_ITEM,
      //   authority: [Role.ADMIN, Role.AGENT],
      //   subMenu: [],
      // },
      {
        key: 'dashboard.comms',
        path: `${DASHBOARDS_PREFIX_PATH}/comms`,
        title: 'Communication',
        translateKey: 'nav.dashboard.comms',
        icon: 'dashboardMails',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN, Role.AGENT],
        subMenu: [],
      },
      {
        key: 'dashboard.todo',
        path: `${DASHBOARDS_PREFIX_PATH}/todo`,
        title: 'Todo',
        translateKey: 'nav.dashboard.todo',
        icon: 'todoIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN, Role.AGENT],
        subMenu: [],
        badge: {
          count: 0,
          color: 'bg-amber-600',
          variant: 'solid',
          max: 99,
        },
      },
      {
        key: 'dashboard.documents',
        path: `${DASHBOARDS_PREFIX_PATH}/documents`,
        title: 'Dcouments',
        translateKey: 'nav.dashboard.documents',
        icon: 'dashboardDocuments',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN],
        subMenu: [],
      },
      {
        key: 'dashboard.openings',
        path: `${DASHBOARDS_PREFIX_PATH}/openings`,
        title: 'Openings',
        translateKey: 'nav.dashboard.openings',
        icon: 'dashboardOpening',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN, Role.AGENT],
        subMenu: [],
      },
      {
        key: 'dashboard.allreclamations',
        path: `${DASHBOARDS_PREFIX_PATH}/reclamations`,
        title: 'Reclamations',
        translateKey: 'nav.dashboard.reclamations.allReclamations',
        icon: 'dashboardReclamations',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.AGENT],
        subMenu: [],
      },

      // {
      //   key: 'dashboard.confirmation',
      //   path: `${DASHBOARDS_PREFIX_PATH}/confirmation`,
      //   title: 'Confirmation',
      //   translateKey: 'nav.dashboard.confirmation',
      //   icon: 'dashboardAcceptedOffers',
      //   type: NAV_ITEM_TYPE_ITEM,
      //   authority: [Role.ADMIN, Role.AGENT],
      //   subMenu: [],
      // },
      // {
      //   key: 'dashboard.payment',
      //   path: `${DASHBOARDS_PREFIX_PATH}/payment`,
      //   title: 'Payment vouchers',
      //   translateKey: 'nav.dashboard.payment',
      //   icon: 'dashboardPaymentVouchers',
      //   type: NAV_ITEM_TYPE_ITEM,
      //   authority: [Role.ADMIN, Role.AGENT],
      //   subMenu: [],
      // },
      // {
      //   key: 'dashboard.netto',
      //   path: `${DASHBOARDS_PREFIX_PATH}/netto`,
      //   title: 'Netto',
      //   translateKey: 'nav.dashboard.netto',
      //   icon: 'dashboardAcceptedOffers',
      //   type: NAV_ITEM_TYPE_ITEM,
      //   authority: [Role.ADMIN, Role.AGENT],
      //   subMenu: [],
      // },
      {
        key: 'housekeeping',
        path: '',
        title: 'Project Settings',
        translateKey: 'nav.housekeeping',
        icon: 'dashboardHousekeeping',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [Role.ADMIN, Role.PROVIDER],
        subMenu: [
          {
            key: 'dashboard.projects',
            path: `${DASHBOARDS_PREFIX_PATH}/projects`,
            title: 'Housekeeping',
            translateKey: 'nav.dashboard.projects.projects',
            icon: 'dashboardProjects',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [Role.ADMIN],
            subMenu: [
              {
                key: 'dashboard.projects.allProjects',
                path: `${DASHBOARDS_PREFIX_PATH}/projects`,
                title: 'All Projects',
                translateKey: 'nav.dashboard.projects.allProjects',
                icon: 'dashboardProjects',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [Role.ADMIN],
                subMenu: [],
              },
              {
                key: 'dashboard.projects.create',
                path: `${DASHBOARDS_PREFIX_PATH}/projects/create`,
                title: 'Create Project',
                translateKey: 'nav.dashboard.projects.create',
                icon: 'dashboardProjects',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [Role.ADMIN],
                subMenu: [],
              },
              {
                key: 'dashboard.projects.closeProjects',
                path: `${DASHBOARDS_PREFIX_PATH}/projects/close-projects`,
                title: 'Close Project',
                translateKey: 'nav.dashboard.projects.closeProjects',
                icon: 'dashboardProjects',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [Role.ADMIN],
                subMenu: [],
              },
            ],
          },
          {
            key: 'dashboard.reclamations',
            path: ``,
            title: 'Reclamations',
            translateKey: 'nav.dashboard.reclamations.reclamations',
            icon: 'dashboardReclamations',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [Role.ADMIN, Role.PROVIDER],
            subMenu: [
              {
                key: 'dashboard.allreclamations',
                path: `${DASHBOARDS_PREFIX_PATH}/reclamations`,
                title: 'All Reclamations',
                translateKey: 'nav.dashboard.reclamations.allReclamations',
                icon: 'dashboardReclamations',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [Role.ADMIN, Role.PROVIDER, Role.AGENT],
                subMenu: [],
              },
              {
                key: 'dashboard.reclamations.pendingReclamations',
                path: `${DASHBOARDS_PREFIX_PATH}/reclamations/pending-reclamations`,
                title: 'Pending Reclamations',
                translateKey: 'nav.dashboard.reclamations.pendingReclamations',
                icon: 'dashboardReclamations',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [Role.PROVIDER],
                subMenu: [],
              },
            ],
          },
        ],
      },
    ],
  },
];

export default dashboardsNavigationConfig;
